# Generated by Django 5.2.1 on 2025-06-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_rol", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "roles",
                    models.IntegerField(
                        choices=[
                            (1, "Esocoge el rol"),
                            (2, "Project Management Officer"),
                            (3, "Facilitador del equipo SCRUM"),
                            (4, "Encargado del desarrollo de software"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
    ]
