# Generated by Django 5.2.1 on 2025-06-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projectusers', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='roles',
        ),
        migrations.AlterField(
            model_name='roles',
            name='name_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projectusers.projectuser'),
        ),
    ]
