# Generated by Django 5.2.1 on 2025-06-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_remove_roles_roles_alter_roles_name_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name_rol',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
