# Generated by Django 5.2.1 on 2025-06-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_roles_name_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name_rol',
            field=models.CharField(choices=[('PMO', 'PMO'), ('Scrum Master', 'Scrum Master'), ('Desarrollador', 'Desarrollador')], max_length=50, null=True),
        ),
    ]
