# Generated by Django 5.2.1 on 2025-05-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_usuario_user_id_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='user_id',
        ),
    ]
