# Generated by Django 5.2.1 on 2025-06-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userstories",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("to_do", "To Do"),
                            ("progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="to_do",
                        max_length=10,
                    ),
                ),
                ("story_items", models.CharField(max_length=100)),
                ("estimated_time", models.CharField(max_length=100)),
                ("user_id", models.IntegerField()),
                ("scrum_id", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userstories",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
