# Generated by Django 5.2.1 on 2025-06-15 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstories',
            name='scrum_id',
        ),
        migrations.RemoveField(
            model_name='userstories',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userstories',
            name='scrum_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scrum_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstories',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userstories', to=settings.AUTH_USER_MODEL),
        ),
    ]
