# Generated by Django 5.2.1 on 2025-05-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='roles',
            field=models.IntegerField(choices=[('1', 'Esocoge el rol'), ('PMO', 'Project Management Officer'), ('SCRUM_M', 'Facilitador del equipo Scrum'), ('DEV', 'Encargado del desarrollo de software')], default=1),
        ),
    ]
