# Generated by Django 5.2.1 on 2025-05-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_roles_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='roles',
            field=models.IntegerField(choices=[(1, 'Esocoge el rol'), (2, 'Project Management Officer'), (3, 'Facilitador del equipo SCRUM'), (4, 'Encargado del desarrollo de software')], default=1),
        ),
    ]
