# Generated by Django 5.2.1 on 2025-06-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projectuser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("PMO", "PMO"),
                            ("Scrum Master", "Scrum Master"),
                            ("Desarrollador", "Desarrollador"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
