# Generated by Django 5.2.1 on 2025-05-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PMO', 'PMO'), ('Scrum Master', 'Scrum Master'), ('Desarrollador', 'Desarrollador')], max_length=50)),
            ],
        ),
    ]
