# Generated by Django 5.2.1 on 2025-05-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projectusers', '0001_initial'),
        ('Users', '0003_rename_id_usuario_user_id_alter_usuario_password'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.usuario'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
