# Generated by Django 5.2.1 on 2025-06-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history_user_id", models.PositiveIntegerField()),
                ("description", models.TextField(null=True)),
                ("state", models.CharField(max_length=100)),
            ],
        ),
    ]
